{{- range $name, $domain := .Values.certificates }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
name: tls-{{ $name }}
spec:
secretName: tls-{{ $name }}
dnsNames:
- {{ $domain }}
acme:
    config:
    - http01:
        ingressClass: nginx
    domains:
    - {{ $domain }}
issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
{{- end }}