# Default values for External DNS.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
domainFilter:
  enabled: true
  filter: "mydomain.com"
  
dnsZoneResourceGroup: "aResourceGroupName"