# Configuration for CertManager to configure LetsEncrypt certificates for domains.
# List certificates here as key-value pairs of certificate name (used to make the resource name in k8s) and domain name
# CertManager will then use LetsEncrypt to create the certificates automatically as required.

certificates:
  #buildingdata: buildingdata.trimbleplatform.net
  #chimera: chimera.trimbleplatform.net

# email address to give to LetsEncrypt
acme-contact-email: mep-devops-team-ug@trimble.com

cert-manager:
  ingressShim:
    defaultIssuerName: "letsencrypt-prod"
    defaultIssuerKind: "ClusterIssuer"