apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "basicservice.fullname" . }}
  labels:
    app: {{ template "basicservice.name" . }}
    chart: {{ template "basicservice.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "basicservice.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "basicservice.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ default "80" .Values.image.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ default "/" .Values.image.livenessProbe }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ default "/" .Values.image.readinessProbe }}
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- if .Values.imageCredentials.enabled -}}
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.name }}
{{- end }}
